// samples/react/src/components/ChartCard.tsx
/**
 * ChartCard — the card chrome shared by every panel on the board.
 *
 * The visible title is a real <h2> in the document outline, NOT a canvas
 * `title` option: card chrome owns the heading, the chart owns `a11y.title`.
 */

import type { ReactNode } from 'react';

/** Column spans that exist in styles.css (`.card--span-*`). */
export type Span = 3 | 4 | 5 | 7 | 8;

export interface ChartCardProps {
  title: string;
  subtitle: string;
  span: Span;
  /** Taller plot for the hero card. */
  hero?: boolean;
  /** Right-hand slot in the card head — e.g. the Reset zoom button. */
  action?: ReactNode;
  /** Announce content changes (the Inspector card). */
  live?: boolean;
  children: ReactNode;
}

export function ChartCard({
  title,
  subtitle,
  span,
  hero = false,
  action,
  live = false,
  children,
}: ChartCardProps) {
  return (
    <article
      className={`card${hero ? ' card--hero' : ''} card--span-${span}`}
      aria-live={live ? 'polite' : undefined}
    >
      <div className="card__head">
        <div>
          <h2 className="card__title">{title}</h2>
          <p className="card__subtitle">{subtitle}</p>
        </div>
        {action}
      </div>
      {children}
    </article>
  );
}

// samples/svelte/src/lib/ChartCard.svelte
<!--
  Card chrome: the visible <h2>/subtitle, an optional head action, and the
  card body as a snippet.

  The heading lives HERE rather than in the canvas (no `title` option is passed
  to any chart), so card titles stay in the document outline. The body snippet
  is normally a chart component given `class="card__chart"` — the wrapper's
  `class` prop puts the sizing class on the very div ChartCraft mounts into.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';

  interface Props {
    title: string;
    subtitle: string;
    /** Grid span, matching the `.card--span-*` utilities in styles.css. */
    span: 3 | 4 | 5 | 7 | 8;
    /** Taller chart well, for the hero card. */
    hero?: boolean;
    /** Announce body changes (the Inspector). */
    live?: boolean;
    /** Optional control rendered at the top-right of the card head. */
    action?: Snippet;
    children: Snippet;
  }

  let { title, subtitle, span, hero = false, live = false, action, children }: Props = $props();
</script>

<article
  class="card card--span-{span}"
  class:card--hero={hero}
  aria-live={live ? 'polite' : undefined}
>
  <div class="card__head">
    <div>
      <h2 class="card__title">{title}</h2>
      <p class="card__subtitle">{subtitle}</p>
    </div>
    {#if action}{@render action()}{/if}
  </div>
  {@render children()}
</article>
