// samples/react/src/components/ChartCard.tsx
/**
 * ChartCard — the card chrome shared by every panel on the board.
 *
 * The visible title is a real <h2> in the document outline, NOT a canvas
 * `title` option: card chrome owns the heading, the chart owns `a11y.title`.
 */

import type { ReactNode } from 'react';

/** Column spans that exist in styles.css (`.card--span-*`). */
export type Span = 3 | 4 | 5 | 7 | 8;

export interface ChartCardProps {
  title: string;
  subtitle: string;
  span: Span;
  /** Taller plot for the hero card. */
  hero?: boolean;
  /** Right-hand slot in the card head — e.g. the Reset zoom button. */
  action?: ReactNode;
  /** Announce content changes (the Inspector card). */
  live?: boolean;
  children: ReactNode;
}

export function ChartCard({
  title,
  subtitle,
  span,
  hero = false,
  action,
  live = false,
  children,
}: ChartCardProps) {
  return (
    <article
      className={`card${hero ? ' card--hero' : ''} card--span-${span}`}
      aria-live={live ? 'polite' : undefined}
    >
      <div className="card__head">
        <div>
          <h2 className="card__title">{title}</h2>
          <p className="card__subtitle">{subtitle}</p>
        </div>
        {action}
      </div>
      {children}
    </article>
  );
}

// samples/vue/src/components/ChartCard.vue
<script setup lang="ts">
/**
 * The card chrome shared by every panel on the board.
 *
 * The visible heading is a real `<h2>` in the document outline — which is why
 * no chart is given a `title` option. Grid span comes in as a number and maps
 * onto the shared stylesheet's `.card--span-N` classes.
 *
 * The default slot holds the chart component itself, NOT a wrapper div: the
 * stylesheet's `.card__chart` carries the height, and the ChartCraft container
 * has to be the element that is actually sized. Callers therefore write
 * `<LineChart class="card__chart" …/>` and the wrapper's root div picks the
 * class up through attribute fallthrough.
 */
const props = defineProps<{
  title: string;
  subtitle?: string;
  /** 12-column grid span: 3, 4, 5, 7 or 8. */
  span: 3 | 4 | 5 | 7 | 8;
  /** Taller chart well, for the hero card. */
  hero?: boolean;
}>();
</script>

<template>
  <article class="card" :class="[`card--span-${props.span}`, { 'card--hero': props.hero }]">
    <div class="card__head">
      <div>
        <h2 class="card__title">{{ props.title }}</h2>
        <p v-if="props.subtitle" class="card__subtitle">{{ props.subtitle }}</p>
      </div>
      <slot name="actions" />
    </div>
    <slot />
  </article>
</template>
